### ISSUE TITLE
実験的な機能: アイデア投稿履歴へのリアクションに `🤔` を追加する

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/idea-reaction#107]
- この機能は `experiments_thinking_emoji` という features を有効にすることで使用できます: `cargo run --feature experiments_thinking_emoji`
- `v0.3.0` ではこの features を有効にしています. 本番環境での評判次第で追加したりする

**Comment by Lucky3028** [comment]
closed by #108
