### ISSUE TITLE
Refactor: replace `mod.rs`

### ISSUE THREAD

**Issue by Lucky3028** [GiganticMinecraft/idea-reaction#110]
https://doc.rust-jp.rs/edition-guide/rust-2018/path-changes.html#%E3%81%95%E3%82%88%E3%81%86%E3%81%AA%E3%82%89modrs
`mod.rs`は後方互換性のために残されている仕様なので、`各サブモジュール名.rs`をルートディレクトリに作成するべきです。

https://github.com/GiganticMinecraft/idea-reaction/blob/main/src/redmine/mod.rs

**Comment by m1sk9** [comment]
普通に知らんかった Rustacean 名乗るのやめます(?)
